### PR TITLE
Dev login

### PR DESCRIPTION
**Pull request by venkatesh-sivaraman**
Previously the localhost login page (`/admin/login`) didn't support redirecting to another dev site like Courseroad. Added this functionality by routing login to a custom view which uses the standard Django `AuthenticationForm`, then generates an access code upon successful authentication.

### CODE REVIEW

**Comment by georgiashay** [comment]
I'm getting a `TemplateDoesNotExist at /dev_login/ ` error - it looks like there isn't a dev_login template file under templates/common

**Comment by venkatesh-sivaraman** [comment]
Oops :')

**Comment by georgiashay** [comment]
Everything's looking good now!  I restarted the dev server and nothing looks broken, although I am not sure how to test this particular PR since the login mode is for local testing only.

**Comment by venkatesh-sivaraman** [comment]
As long as it works locally and doesn't break the main login system, we should be good 😁 I'm sending you a doc with more detailed server instructions, please take a look at that as you deploy to prod! It shouldn't have anything beyond the instructions I already gave you in this case, but there's some useful stuff you might need for more involved updates.

**Comment by georgiashay** [comment]
Deployed to prod, everything looks good!

**Pull request merged**
