### PR TITLE
Improved local setup

### PR DESCRIPTION
**Pull request by venkatesh-sivaraman**
Adds clearer instructions and automation for how to set up a FireRoad instance locally.

* Improved instructions in the main `readme.md`, and a new `data/readme.md` file describing catalog data structure
* Catalogs are now stored in `data/catalogs` by default instead of making you choose a location
* New `courseupdater/download_data` endpoint that returns a zipped catalog directory, which can be dropped into the `data` directory for easy setup
* New `setup_catalog.sh` script which prompts you to download the data or creates an empty initialized catalog directory for you
* Add CORS middleware for testing other frontend services locally

### CODE REVIEW

**Comment by venkatesh-sivaraman** [comment]
@georgiashay could you run through the new steps in the readme on a fresh install and see if you’re able to set it up? Note that this PR branch is deployed on dev but not prod, so when the setup script prompts you to download the catalog, for now you’ll have to go to the equivalent fireroad-dev url instead of fireroad.

Let me know if you have any difficulties or suggestions for how it could be made even easier!

**Comment by georgiashay** [comment]
I am stuck on the downloading catalog step.  I have tried 3 browsers but the URL is always giving me some sort of "too many redirects" error.  Just to check, is the correct url https://fireroad-dev.mit.edu/courseupdater/download_data?

**Comment by venkatesh-sivaraman** [comment]
It could be a Touchstone login issue - are you able to log in through the Login button on fireroad-dev.mit.edu? If so then you should be able to go to the same link again and it will work, or you can also find it in the Admin menu of the nav bar on the home page.

**Comment by georgiashay** [comment]
I am able to login fine on fireroad-dev.mit.edu, but going to the link still doesn't work.  It looks like I don't have admin access on the dev server as I don't have the Admin menu on fireroad-dev.mit.edu (I do on fireroad.mit.edu).

**Comment by venkatesh-sivaraman** [comment]
Ahh that makes sense. I'll debug the 'too many redirects' thing, but in the meantime you should have staff user access now.

**Comment by georgiashay** [comment]
Thanks!  

If I follow the setup steps I get `no such table: analytics_requestcount` when I try to run it.  The issue goes away if I add a migrations folder with empty __init__.py in the analytics folder and run migrate again.

**Comment by georgiashay** [comment]
Also, it looks like the original link to download the catalog works fine now that I have staff user access, so the redirects error is probably related to that.

**Comment by venkatesh-sivaraman** [comment]
The analytics issue was because that table wasn't set to migrate in the setup script - should be fixed now. And that admin user thing should result in a 403 error... it's tricky to debug because accounts are one-to-one with kerberoses, so I can't log in as a staff user. I may temporarily disable admin access on dev later tonight to debug.

**Comment by georgiashay** [comment]
Sounds good.  I did the setup process from scratch again and it's working fine.  It might be nice to add a line to the readme with the command to start the server.  Other than that, looks good to me

**Comment by venkatesh-sivaraman** [comment]
Can't believe that wasn't in the readme 🤦🏾‍♂️ Thanks for your eyes on this! Hopefully it simplifies your instructions to anyone who's trying to clone FireRoad in the future. I'll go ahead and merge, and take a look at the login issue separately.

**Pull request merged**
