### PR TITLE
Fix unicode errors

### PR DESCRIPTION
**Pull request by georgiashay**
I was getting errors in django admin and in the requirements list for lists with unicode en dashes or greater than or equal to symbols. This should fix these unicode errors

### CODE REVIEW

**Comment by georgiashay** [comment]
I may actually just have a really old codebase since it looks like this may have been fixed on master? Let me look into this because I was definitely getting errors in production as well.

**Comment by georgiashay** [comment]
Okay fixed the errors on a more recent version of the code.

**Comment by georgiashay** [comment]
Can confirm this fixes the bug on dev. Will pull this on prod as well since it is preventing editing of major 18

**Comment by venkatesh-sivaraman** [comment]
Sounds good and edits look good, I can just merge it now!

**Pull request merged**
